name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - cmake: 1.18.0
            conan: 1_27_0
            clang: 10
    steps:
    - uses: actions/checkout@v2
      
    - name: Build base image
      uses: docker/build-push-action@v1.1.0
      with:
        dockerfile: Dockerfile.base
        repository: jonasprogrammer/dev-tools
        tags: base-cm${{matrix.cmake}}-cn${{matrix.conan}}
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}
    - name: Build clang image
      uses: docker/build-push-action@v1.1.0
      with:
        dockerfile: Dockerfile.clang
        repository: jonasprogrammer/dev-tools
        tags: clang-${{matrix.clang}}-cm${{matrix.cmake}}-cn${{matrix.conan}}
        build_args: BASE_IMAGE=jonasprogrammer/dev-tools:base-cm${{matrix.cmake}}-cn${{matrix.conan}},LLVM_VERSION=${{matrix.clang}}
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}
    - name: Build ssh image
      uses: docker/build-push-action@v1.1.0
      with:
        dockerfile: Dockerfile.clang
        repository: jonasprogrammer/dev-tools
        tags: ssh-clang-${{matrix.clang}}-cm${{matrix.cmake}}-cn${{matrix.conan}}
        build_args: BASE_IMAGE=jonasprogrammer/dev-tools:clang-${{matrix.clang}}-cm${{matrix.cmake}}-cn${{matrix.conan}}
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}
