name: CI-Scripting

on:
  push:
    branches: [ scripting ]
  workflow_dispatch:

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - ruby: 2.6
          - ruby: 3.1
          - ruby: 3.2
    steps:
    - uses: actions/checkout@v2

    - name: Setup ruby build
      if: ${{matrix.ruby}}
      run: |
        echo "BUILD_TAG=ruby-${{matrix.ruby}}" >> $GITHUB_ENV
        echo "BASE_IMAGE=ruby:${{matrix.ruby}}" >> $GITHUB_ENV
        echo "DOCKERFILE=ruby" >> $GITHUB_ENV

    - name: Setup conda build
      if: ${{matrix.conda}}
      run: |
        echo "BUILD_TAG=conda-${{matrix.conda}}" >> $GITHUB_ENV
        echo "BASE_IMAGE=continuumio/anaconda3:${{matrix.conda}}" >> $GITHUB_ENV
        echo "DOCKERFILE=conda" >> $GITHUB_ENV

    - name: Build base image
      uses: docker/build-push-action@v1.1.0
      with:
        dockerfile: Dockerfile.${{env.DOCKERFILE}}
        repository: jonasprogrammer/dev-tools
        tags: ${{env.BUILD_TAG}}
        build_args: BASE_IMAGE=${{env.BASE_IMAGE}}
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}

    - name: Build ssh image
      uses: docker/build-push-action@v1.1.0
      with:
        dockerfile: Dockerfile.ssh
        repository: jonasprogrammer/dev-tools
        tags: ssh-${{env.BUILD_TAG}}
        build_args: BASE_IMAGE=jonasprogrammer/dev-tools:${{env.BUILD_TAG}}
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}
